# Generated by Django 5.2.7 on 2025-10-31 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avisina', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='class_name',
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
