# Generated by Django 5.2.7 on 2025-10-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avisina', '0003_classes_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
