# Generated by Django 5.2.4 on 2025-11-06 19:01

import avisina.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisina', '0005_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='video',
        ),
        migrations.AddField(
            model_name='teacher',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='teacher/pdf', validators=[avisina.models.validate_teacher_file]),
        ),
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.CharField(default='title', max_length=30),
            preserve_default=False,
        ),
    ]
