# Generated by Django 5.2.4 on 2025-11-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisina', '0007_alter_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='parsa', max_length=30),
            preserve_default=False,
        ),
    ]
